# https://www.mkdocs.org/user-guide/configuration/

site_name: Tilezen Docs
repo_url: https://github.com/tilezen/vector-datasource/
nav:
  - Introduction: index.md
#  - Introduction for Users: valhalla-intro.md
#  - Terminology: terminology.md
  - Public APIs:
    - Layers Overview: layers.md
    - "Display Tiles": display-tiles.md
    - "Use Service": use-service.md
    - "API Keys and Rate Limits": api-keys-and-rate-limits.md
  - Data sources:
    - Data sources: data-sources.md
    - Attribution requirements: attribution.md
  - Development:
    - Changelog: ../CHANGELOG.md
    - SemVer: ../SEMANTIC-VERSIONING.md
    - Contributing: ../CONTRIBUTING.md
    - Tests: ../TESTS.md
    - Performance: ../PERFORMANCE.md
#    - releasing.md
  
theme: readthedocs
markdown_extensions:
  - toc:
      permalink: True
